GeneralGlobalConfig = require("Envir/Extension/DirectorDir/Config/通用/cfg_全局配置.lua")
require("Envir/Extension/DirectorDir/Config/通用/cfg_禁止脱下的装备.lua")

GeneralAppOpenChargeWnd = require("Envir/Extension/game/通用脚本/打开充值.lua")
GeneralForceGuideData = require("Envir/Extension/game/通用脚本/强引导.lua")
GlobalReliveData = require("Envir/Extension/game/通用脚本/复活功能.lua")
GlobalQuickHelperData = require("Envir/Extension/game/通用脚本/快捷服务.lua")
GeneralAutoFightData = require("Envir/Extension/game/通用脚本/挂机功能.lua")
GeneralLoginLimitData = require("Envir/Extension/game/通用脚本/封测脚本.lua")
GeneralTopIcon = require("Envir/Extension/game/通用脚本/右上图标.lua")
GeneralClientAction = require("Envir/Extension/game/通用脚本/客户端综合操作.lua")
CSDataSyncUtil = require("Envir/Extension/game/通用脚本/CSDataSyncUtil.lua")
GeneralSpecialItem = require("Envir/Extension/game/通用脚本/特殊属性道具.lua")
ChooseJob = require("Envir/Extension/game/通用脚本/职业选择.lua")
AddBtnxdtUI = require("Envir/Extension/game/通用脚本/小地图.lua")
_PlayVar = require("Envir/Extension/game/通用脚本/自定义变量操作.lua")
