mfyqSkill = require("Envir/Extension/game/skill/魔法源泉.lua")
fszxSkill = require("Envir/Extension/game/skill/法师之心.lua")
slzsSkill = require("Envir/Extension/game/skill/死灵之手.lua")
wldjSkill = require("Envir/Extension/game/skill/亡灵大军.lua")
sldfSkill = require("Envir/Extension/game/skill/死灵大法.lua")
bzgcSkill = require("Envir/Extension/game/skill/爆炸蛊虫.lua")
sycwSkill = require("Envir/Extension/game/skill/饲养虫王.lua")
chtbSkill = require("Envir/Extension/game/skill/召唤天兵.lua")
hsfzSkill = require("Envir/Extension/game/skill/幻术复制.lua")
lsqysSkill = require("Envir/Extension/game/skill/临时契约术.lua")
xfzSkill = require("Envir/Extension/game/skill/旋风斩.lua")
require("Envir/Extension/game/skill/狂暴血液.lua")
require("Envir/Extension/game/skill/抱月剑气.lua")
require("Envir/Extension/game/skill/鬼武者_附体.lua")
require("Envir/Extension/game/skill/嘲讽妖兽.lua")
shzxSkill = require("Envir/Extension/game/skill/守护之心.lua")
qszqSkill = require("Envir/Extension/game/skill/骑士之躯.lua")
require("Envir/Extension/game/skill/圣骑回血.lua")
wlhdSkill = require("Envir/Extension/game/skill/五雷轰顶.lua")
xlhjSkill = require("Envir/Extension/game/skill/心灵幻境.lua")
gwzSkill = require("Envir/Extension/game/skill/地狱鬼爪-鬼武者.lua")
sqsSkill = require("Envir/Extension/game/skill/地狱鬼爪-圣骑士.lua")
