require("Envir/Extension/game/sys/通用功能.lua")
require("Envir/Extension/game/sys/双击道具.lua")
require("Envir/Extension/game/sys/定时器.lua")
SystemRobotData = require("Envir/Extension/game/sys/机器人.lua")
require("Envir/Extension/game/sys/装备穿脱.lua")
TitleShow = require("Envir/Extension/game/sys/称号操作.lua")
require("Envir/Extension/game/sys/受伤触发.lua")
require("Envir/Extension/game/sys/攻击触发.lua")
require("Envir/Extension/game/sys/货币改变.lua")
require("Envir/Extension/game/sys/道具拾取.lua")
require("Envir/Extension/game/sys/掉落检测.lua")
require("Envir/Extension/game/sys/登录触发.lua")
require("Envir/Extension/game/sys/离线触发.lua")
require("Envir/Extension/game/sys/交易触发.lua")
require("Envir/Extension/game/sys/BUFF触发.lua")
require("Envir/Extension/game/sys/技能触发.lua")
require("Envir/Extension/game/sys/主表单.lua")
GeneralNewManData = require("Envir/Extension/game/sys/新人上线.lua")
